- name: EBS Scaling Automation (New Tickets Only)
  hosts: ec2-server
  become: yes
  gather_facts: yes

  roles:
    - servicenow_fetch

  tasks:

    - name: Process each CR
      include_tasks: process.yml
      loop: "{{ cr_list }}"
      loop_control:
        loop_var: cr
