- name: Process ONLY Latest CR
  hosts: ec2-server
  become: yes
  gather_facts: yes

  roles:
    - servicenow_fetch

  tasks:

    - name: Process latest CR only
      include_tasks: process.yml
      vars:
        cr: "{{ latest_cr }}"
