- name: Build ServiceNow query (URL encoded)
  set_fact:
    snow_query: "{{ 'short_descriptionLIKEDisk Scale EBS^state=New' | urlencode }}"

- name: Fetch Change Requests
  uri:
    url: "{{ snow_instance }}/api/now/table/change_request?sysparm_query={{ snow_query }}"
    method: GET
    user: "{{ snow_user }}"
    password: "{{ snow_password }}"
    force_basic_auth: yes
    return_content: yes
    headers:
      Accept: "application/json"
  register: cr_response

- name: Show Ticket Numbers
  debug:
    msg: "Processing Change Request: {{ item.number }}"
  loop: "{{ cr_response.json.result }}"

- name: Store CR list
  set_fact:
    cr_list: "{{ cr_response.json.result }}"
